[package]
name = "rust_ba"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbr = "1.0.4"
glob = "0.3.0"
clap = "2.33.3"
rayon = "1.5.1"
vtracer = "0.3.0"
visioncortex = "0.4.0"
